CREATE TABLE beer (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version INTEGER,
    beer_name VARCHAR(255),
    beer_style VARCHAR(255),
    upc VARCHAR(255),
    quantity_on_hand INTEGER,
    price DECIMAL(19, 2),
    create_date TIMESTAMP,
    update_date TIMESTAMP
);
