-- Create customer table
CREATE TABLE customer (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version INTEGER,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255),
    phone_number VARCHAR(255),
    address_line1 VARCHAR(255) NOT NULL,
    address_line2 VARCHAR(255),
    city VARCHAR(255) NOT NULL,
    state VARCHAR(255) NOT NULL,
    zip_code VARCHAR(255) NOT NULL,
    create_date TIMESTAMP,
    update_date TIMESTAMP
);

-- Insert a default customer for existing orders
INSERT INTO customer (name, address_line1, city, state, zip_code, create_date, update_date)
VALUES ('Default Customer', 'Default Address', 'Default City', 'Default State', '00000', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- Add customer_id column to beer_order table
ALTER TABLE beer_order
    ADD COLUMN customer_id INTEGER;

-- Update existing beer_order records to use the default customer
UPDATE beer_order SET customer_id = (SELECT id FROM customer WHERE name = 'Default Customer');

-- Add foreign key constraint
ALTER TABLE beer_order ADD CONSTRAINT fk_beer_order_customer
    FOREIGN KEY (customer_id) REFERENCES customer(id);

-- Drop the customer_ref column
ALTER TABLE beer_order
    DROP COLUMN customer_ref;
