-- Create beer_order table
CREATE TABLE beer_order (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version INTEGER,
    customer_ref VARCHAR(255) NOT NULL,
    payment_amount DECIMAL(19, 2) NOT NULL,
    order_status VARCHAR(50) NOT NULL,
    create_date TIMESTAMP,
    update_date TIMESTAMP
);

-- Create beer_order_line table
CREATE TABLE beer_order_line (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version INTEGER,
    beer_order_id INTEGER NOT NULL,
    beer_id INTEGER NOT NULL,
    order_quantity INTEGER NOT NULL,
    quantity_allocated INTEGER,
    line_status VARCHAR(50) NOT NULL,
    create_date TIMESTAMP,
    update_date TIMESTAMP,
    FOREIGN KEY (beer_order_id) REFERENCES beer_order(id),
    FOREIGN KEY (beer_id) REFERENCES beer(id)
);